service: aws-test-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors: true

      - http:
          path: /{proxy}
          method: any
          cors: true
